const images = {
    adrianoreidel: require('./adrianojosemazurekreidel.png'),
    fullstacksoftwaredeveloper: require('./fullstacksoftwaredeveloper.png'),
    craftingtable: require('./crafting-limpa.jpeg'),
    livrobranco: require('./livrobranco.png'),
    sobre: require('./sobre.png'),
    sobre2: require('./sobre2.png'),
    experiencias: require('./experiencias.png'),
    experiencias2: require('./experiencias2.png'),
    contato: require('./contato.png'),
    contato2: require('./contato2.png'),
    projetos: require('./projetos.png'),
    projetos2: require('./projetos2.png'),
    livrosobre: require('./livrosobre.png'),
    livrosobre2: require('./livrosobre2.PNG'),
    livroexperiencias: require('./livroexperiencias.png'),
    livroprojetos: require('./livroprojetos.png'),
    livrocontato: require('./livrocontato.png'),
    setadireita: require('./setadireita.png'),
    setaesquerda: require('./setaesquerda.png'),
    pincel: require('./pincel.png'),
    linkedin: require('./linkedin.png'),
    github: require('./github.png'),
    email: require('./email.png'),
    csharp: require('./csharp.jpeg'),
    dotNetCore: require('./dotnetcore.jpeg'),
    postgre: require('./postgre.jpeg'),
    javascript: require('./javascript.jpeg'),
    extjs: require('./extjs.jpeg'),
    sybase: require('./sybase.jpeg'),
    git: require('./git.jpeg'),
    gitlab: require('./gitlab.jpeg'),
    nhibernate: require('./nhibernate.jpeg'),
    nodejs: require('./node.jpeg'),
    vs: require('./vs.jpeg'),
    vscode: require('./vscode.jpeg'),
    react: require('./react.jpeg'),
    htmlicon: require('./htmlicon.jpeg'),
    cssicon: require('./cssicon.jpeg'),
    python: require('./python.jpeg'),
    c: require('./c.jpeg'),
    java: require('./java.jpeg'),
  };
  
  export default images;
