const images = {
    adrianoreidel: require('./adrianojosemazurekreidel.png'),
    fullstacksoftwaredeveloper: require('./fullstacksoftwaredeveloper.png'),
    craftingtable: require('./crafting-limpa.jpeg'),
    livrobranco: require('./livrobranco.png'),
    sobre: require('./sobre.png'),
    sobre2: require('./sobre2.png'),
    experiencias: require('./experiencias.png'),
    experiencias2: require('./experiencias2.png'),
    contato: require('./contato.png'),
    contato2: require('./contato2.png'),
    projetos: require('./projetos.png'),
    projetos2: require('./projetos2.png'),
    livrosobre: require('./livrosobre.png'),
    livrosobre2: require('./livrosobre2.PNG'),
    livroexperiencias: require('./livroexperiencias.png'),
    livroprojetos: require('./livroprojetos.png'),
    livrocontato: require('./livrocontato.png'),
    setadireita: require('./setadireita.png'),
    setaesquerda: require('./setaesquerda.png'),
    pincel: require('./pincel.png'),
    linkedin: require('./linkedin.png'),
    github: require('./github.png'),
    email: require('./email.png'),
    csharp: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg',
    dotNetCore: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dotnetcore/dotnetcore-original.svg',
    postgre: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg',
    javascript: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
    extjs: require('./extjs.jpeg'),
    sybase: require('./sybase.jpeg'),
    git: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg',
    gitlab: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/gitlab/gitlab-original.svg',
    nhibernate: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nhibernate/nhibernate-original.svg',
    nodejs: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg',
    vs: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/visualstudio/visualstudio-original.svg',
    vscode: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg',
    react: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg',
    htmlicon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg',
    cssicon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg',
    python: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg',
    c: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg',
    java: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg',
  };
  
  export default images;
