const images = {
    adrianoreidel: require('./adrianojosemazurekreidel.png'),
    jrfullstacksoftwaredeveloper: require('./jrfullstacksoftwaredeveloper.png'),
    craftingtable: require('./craftingtable.jpeg'),
    livrobranco: require('./livrobranco.png'),
    sobre: require('./sobre.png'),
    sobre2: require('./sobre2.png'),
    experiencias: require('./experiencias.png'),
    experiencias2: require('./experiencias2.png'),
    contato: require('./contato.png'),
    contato2: require('./contato2.png'),
    projetos: require('./projetos.png'),
    projetos2: require('./projetos2.png'),
    livrosobre: require('./livrosobre.png'),
    livrosobre2: require('./livrosobre2.PNG'),
    livroexperiencias: require('./livroexperiencias.png'),
    livroprojetos: require('./livroprojetos.png'),
    livrocontato: require('./livrocontato.png'),
    setadireita: require('./setadireita.png'),
    setaesquerda: require('./setaesquerda.png'),
    pincel: require('./pincel.png'),
    linkedin: require('./linkedin.png'),
    github: require('./github.png'),
    email: require('./email.png'),
  };
  
  export default images;
